name: Wen Build
on: 
  push:
    branches: [ master ]
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          clang -o tests/test tests/test.c
          ./tests/test

  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build tests
        run: |
          ${{ matrix.cc }} -o tests/test tests/test.c
          ./tests/test

  windows:
    runs-on: windows-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build tests
        shell: cmd
        # cl.exe isn't available as-is in Github images because they don't want
        # to, so we need to pull env vars ourselves. Refs:
        # https://github.com/actions/runner-images/issues/6205#issuecomment-1241573412
        # https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#create-your-own-command-prompt-shortcut
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cd tests
          cl.exe /Fe:test test.c
          test.exe
